# .github/workflows/price_ingest.yml
name: Price Ingest
# on:
#  schedule:
#    - cron: '0 5 * * *'        # daily 05:00 UTC
#  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install project
        run: pip install .

      - name: Run ingest
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        run: |
          python - <<'PY'
          from roborisk.datafeed import ingest
          ingest(['AAPL','MSFT','SPY','QQQ','TSLA'])
          PY

      - name: Upload DB artifact
        uses: actions/upload-artifact@v4
        with:
          name: prices-db
          path: roborisk/prices.db
